
/**************************************************************
 *	
 *	fireSound, 8 bit, 11025Hz,
 *	1 channel, 24608 bytes/channel
 *	Total Size: 1 * 24608 + 4 (header) = 24652 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Swimdawg/Documents/cs2261/Fireballs_FinalProject/M03/fireSound.wav
 *	Time-stamp: Tue Nov 28 13:01:33 2017
 *	
 **************************************************************/

#ifndef __FIRESOUNDH__
#define __FIRESOUNDH__

#define FIRESOUNDFREQ 11025
#define FIRESOUNDLEN 24608

extern const unsigned char fireSound[24608];

#endif /* __FIRESOUNDH__ */
