
/**************************************************************
 *	
 *	GameSong2, 8 bit, 11025Hz,
 *	1 channel, 4393152 bytes/channel
 *	Total Size: 1 * 4393152 + 4 (header) = 4393196 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Swimdawg/Documents/cs2261/Fireballs_FinalProject/M03/GameSong2.wav
 *	Time-stamp: Tue Nov 28 01:42:23 2017
 *	
 **************************************************************/

#ifndef __GAMESONG2H__
#define __GAMESONG2H__

#define GAMESONG2FREQ 11025
#define GAMESONG2LEN 4393152

extern const unsigned char GameSong2[4393152];

#endif /* __GAMESONG2H__ */
