
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 2742336 bytes/channel
 *	Total Size: 1 * 2742336 + 4 (header) = 2742380 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Swimdawg/Documents/cs2261/Fireballs_FinalProject/M03/GameSong.wav
 *	Time-stamp: Tue Nov 28 01:08:33 2017
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 2742336

extern const unsigned char GameSong[2742336];

#endif /* __GAMESONGH__ */
