
/**************************************************************
 *	
 *	LoseSong, 8 bit, 11025Hz,
 *	1 channel, 2156255 bytes/channel
 *	Total Size: 1 * 2156255 + 4 (header) = 2156299 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Swimdawg/Documents/cs2261/Fireballs_FinalProject/M03/LoseSong.wav
 *	Time-stamp: Tue Nov 28 14:35:50 2017
 *	
 **************************************************************/

#ifndef __LOSESONGH__
#define __LOSESONGH__

#define LOSESONGFREQ 11025
#define LOSESONGLEN 2156255

extern const unsigned char LoseSong[2156255];

#endif /* __LOSESONGH__ */
