
/**************************************************************
 *	
 *	TitleSong, 8 bit, 11025Hz,
 *	1 channel, 1999872 bytes/channel
 *	Total Size: 1 * 1999872 + 4 (header) = 1999916 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Swimdawg/Documents/cs2261/Fireballs_FinalProject/M03/TitleSong.wav
 *	Time-stamp: Tue Nov 28 00:34:53 2017
 *	
 **************************************************************/

#ifndef __TITLESONGH__
#define __TITLESONGH__

#define TITLESONGFREQ 11025
#define TITLESONGLEN 1999872

extern const unsigned char TitleSong[1999872];

#endif /* __TITLESONGH__ */
