
/**************************************************************
 *	
 *	ultimate, 8 bit, 11025Hz,
 *	1 channel, 27072 bytes/channel
 *	Total Size: 1 * 27072 + 4 (header) = 27116 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Swimdawg/Documents/cs2261/Fireballs_FinalProject/M03/ultimate.wav
 *	Time-stamp: Thu Nov 30 00:43:10 2017
 *	
 **************************************************************/

#ifndef __ULTIMATEH__
#define __ULTIMATEH__

#define ULTIMATEFREQ 11025
#define ULTIMATELEN 27072

extern const unsigned char ultimate[27072];

#endif /* __ULTIMATEH__ */
