
/**************************************************************
 *	
 *	WinSong, 8 bit, 11025Hz,
 *	1 channel, 1410624 bytes/channel
 *	Total Size: 1 * 1410624 + 4 (header) = 1410668 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	/Users/Swimdawg/Documents/cs2261/Fireballs_FinalProject/M03/WinSong.wav
 *	Time-stamp: Tue Nov 28 14:30:09 2017
 *	
 **************************************************************/

#ifndef __WINSONGH__
#define __WINSONGH__

#define WINSONGFREQ 11025
#define WINSONGLEN 1410624

extern const unsigned char WinSong[1410624];

#endif /* __WINSONGH__ */
